@startuml Generation_Algo

title ==GenerationAlgorithm==

loop 50 times
Gene->InitialGenomsPopulation: Create a random gene
end

activate InitialGenomsPopulation
Actor Gene
Actor Child

loop Keep looping all the possible moves have been made
Gene --> Tetris: Makes a move
Tetris --> Gene: GetData
Gene --> Gene: Rate the move made by the gene
end
Gene --> Tetris: GetBestMove
loop Loop over InitialGenomsPopulation and sort the array in descending order
InitialGenomsPopulation --> Gene: Copy the best genes to new array
end

loop Select tuples from finest genes and create 50 children
Gene --> Crossover: 2 Gene are going to pair and randomly exchange their chromosomes;
create Child
Crossover --> Child: the random chromosomes selection create a new gene ( child )
Child --> Mutation: Child can have some mutation
Child --> Children: Store the child in an array of children
end

@enduml
