@startuml Teturisu

title ==General Sequence Diagram==

actor User

==Initiate scripts==
create main
User -> main: User visits the website
activate main
create Tetris
main -> Tetris: new Tetris()
create AI
main -> AI: new AI()


==Game==
User -> main: Start game
main -> Tetris: startGame()
activate Tetris
main -->> User: Continuously show game

note left
one of the two loops in the alt is always
active until the user leaves the website
end note

alt User plays
    loop User plays Tetris
        User -> main: Press key
        main -->> User: Display message "Player plays!"
        main-> Tetris: keyHandler(k)
        else User loses
            Tetris -> main: tetris.died = true
            main -->> User: Display message "Game Over"
        else User starts AI
            User -> main: Start AI (end this loop, start loop below)
            main -> Tetris: tetris.aiActivated = true
            main -> AI
            Activate AI
            main -> main: auto()
            main -->> User: Display AI genes
    end

else AI plays
    loop AI plays Tetris (500 moves per game)
        main -> main: algorithm()
        else AI loses or runs out of moves
            main -> Tetris: tetrisReset
            main -> AI: populate()
            main -> main: algorithm()
        else User lets best AI play
            main -> main: bestAI()
        else User stops AI
            User -> main: Stop AI (end this loop, restart loop above)
            main -> Tetris: aiActivated = false
    end
end

@enduml