@startuml generalActivity

title ==General Activity Diagram==

(*) --> "Start Tetris"
-->"User"
if "tetris.aiActivated" then
-down->[true] "AI plays"
else
-left->[false] "User plays"
-->[User loses] "Game Over"
endif
partition AI {
    "AI plays"-down->"AI"
    if " bestActivated"
    -left->[true] Let best genes play
    else
    -right->[false] CreateInitialPopulation
    endif
    --> Play until loss or has done more than 500 moves
    if "isGeneration5000"
    -left->[true] "Play until loss or has done more than 500 moves"
    else
    -left->[false] Evolve
    -up-> Play until loss or has done more than 500 moves
    endif
}

-up->[tetris.aiActivated = false] User

"Game Over" --> (*)

@enduml 