@startuml generalActivity

title ==General Activity Diagram==

(*) --> "Start Tetris"
-->"User"
if "Enable AI" then
-down->[true] "AI"
else
-left->[false] "User plays"
-->[User loses] "Game Over"
endif

partition AI {
    -up->"AI"
    if "best_activated"
    -left->[true] Let best genes play
    else
    -right->[false] CreateInitialPopulation
    endif
    --> Play until loss or has done more than 500 moves
    if "isGeneration50000"
    -left->[true] "Play until loss or has done more than 500 moves"
    else
    -left->[false] Evolve
    -up-> Play until loss or has done more than 500 moves
    endif
}
-up->[User asks to play] User


"Game Over" --> (*)

@enduml 